name: Update My Blog Posts

on:
    schedule:
    - cron: '0 0 * * *'
    - cron: '0 12 * * *'
    workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://shivam-sharma.hashnode.dev/rss.xml"
